export const Users = [
    {
        id: 1,
        profilePicture: "person/1.jpeg",
        username: "Jahan Malik",
    },
    {
        id: 2,
        profilePicture: "person/2.jpeg",
        username: "Nirob Hasan",
    },
    {
        id: 3,
        profilePicture: "person/3.jpeg",
        username: "Jannat Aritry",
    },
    {
        id: 4,
        profilePicture: "person/4.jpeg",
        username: "Fatema Rahman",
    },
    {
        id: 5,
        profilePicture: "person/5.jpeg",
        username: "Nafisa Islam",
    },
    {
        id: 6,
        profilePicture: "person/6.jpeg",
        username: "Shirley Beauchamp",
    },
    {
        id: 7,
        profilePicture: "person/7.jpeg",
        username: "Travis Bennett",
    },
    {
        id: 8,
        profilePicture: "person/8.jpeg",
        username: "Fatema Akter",
    },
    {
        id: 9,
        profilePicture: "person/9.jpeg",
        username: "Gary Duty",
    },
    {
        id: 10,
        profilePicture: "person/10.jpeg",
        username: "Kajol Akter",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "post/1.jpeg",
        date: "5 mins ago",
        userId: 1,
        react: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "post/2.jpeg",
        date: "15 mins ago",
        userId: 2,
        react: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "post/3.jpeg",
        date: "1 hour ago",
        userId: 3,
        react: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "post/4.jpeg",
        date: "4 hours ago",
        userId: 4,
        react: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "post/5.jpeg",
        date: "5 hours ago",
        userId: 5,
        react: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "post/6.jpeg",
        date: "1 day ago",
        userId: 6,
        react: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Never regret anything that made you smile.",
        photo: "post/7.jpeg",
        date: "2 days ago",
        userId: 7,
        react: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "post/8.jpeg",
        date: "3 days ago",
        userId: 8,
        react: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "Change the world by being yourself.",
        photo: "post/9.jpeg",
        date: "5 days ago",
        userId: 9,
        react: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "post/10.jpeg",
        date: "1 week ago",
        userId: 10,
        react: 104,
        comment: 12,
    },
];